[book]
authors = ["zeramorphic"]
language = "en"
multilingual = false
src = "src"
title = "Quill and Feather specifications"

[output.html]
mathjax-support = true

# Uncomment to enable PDF output.
# [output.pdf]
